= Asciidoctor Demo
Richard Gross <https://github.com/Richargh/>
:experimental:
:toc: preamble
:toc-title: pass:[<b>Contents</b>]

This Demo is inspired by the https://github.com/opendevise/asciidoc-samples/blob/master/demo.adoc[opendevice sample], the link:https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[AsciiDoc Quick Reference] and the link:https://gist.github.com/dcode/0cfbf2699a1fe9b46ff04c41721dda74[Github Flavored Asciidoctor Gist].

It uses Asciidoctor in version {asciidoctor-version} and the content order is based on how often you might use it.

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
ifndef::env-github[]
:idprefix:
:idseparator: -
endif::[]

:numbered!:
[abstract]
== Example Abstract
The optional abstract (one or more paragraphs) goes here.

:numbered:
////
This is a  multi-line comment.
////


// This is a single-line comment.

== Markup

*bold* and **b**older +
_italic_ and __i__talicer +
*_bold italic_*

There is also +
^super^script and ~sub~script +
`monospace` and un``monospaced``

=== Html markup

Use html directly for document edits to show +++<del>deleted</del> and <ins>inserted</ins>+++ text or for +++<s>not accurate stuff</s>+++.

== Links

:google: link:https://google.com

Can go to external sites like {google}[Google] or to relative link:README.adoc[documents].

== Lists

=== Unordered

* Unordered 1
** Nested 2
* level 1

=== Ordered
. Ordered 1
.. and nested 2
. level 1

=== Checklist

* [*] checked
* [x] also checked
* [ ] not checked
*     normal list item

== Blocks

=== Admonition

NOTE: This is a note

Here are the other built-in admonition types:

TIP: Pro tip
that could go on and on...

IMPORTANT: Don't forget...

WARNING: Watch out for...

CAUTION: Ensure that...

[NOTE]
====
This is a longer note with

.A list
- one
- two
- three
====


=== Code

Reference code like `types` or `methods` inline 

or as a block with callouts

[source,ruby]
----
require 'sinatra' // <1>

get '/hi' do // <2>
  "Hello World!" // <3>
end
----
<1> Library import
<2> URL mapping
<3> HTTP response body

== Attributions

=== Bibliography

_The Pragmatic Programmer_ <<pp>> should be required reading for all developers.
To learn all about design patterns, refer to the book by the "`Gang of Four`" <<gof>>.

You will find these books in the <<bib>>.

=== Footnotes

A bold statement!footnoteref:[disclaimer,Opinions are my own.]

Another bold statement with a reused footnote.footnoteref:[disclaimer]

=== Glossary

This is a reference to the <<glossaryentry>> in the <<glossary>>.

=== Quote

[quote, Charles Lutwidge Dodgson]
____
If you don't know where you are going, any road will get you there.
____
{empty} +
[quote, Albert Einstein]
A person who never made a mistake never tried anything new.
{empty} +
____
If you don't know where you are going, any road will get you there.
____


== Image

You can reference images image:icons/fontawesome/solid/anchor.svg[Anchor,10,10 title="Anchor"] inline or as a block:

.An amazing anchor
[#img-anchor]
[caption="Figure 1: "]
image::icons/fontawesome/solid/anchor.svg[Anchor,300,200]


== Diagram

Diagrams can be drawn with mermaid
[mermaid, test, png]   
.... 
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
....

== Tables

[cols="1,1,3", options="header"] 
.with three columns, a header, and one row of content
|===
|Name
|Role
|Description

|Lord McTavish
|Father
|An idiot. That's it.

|===

== Tricks

=== Horizontal Rule

Content

'''

can be separated.

=== Substitution

:url-home: https://asciidoctor.org
:summary: Asciidoctor is a mature, plain-text document format for \
     writing notes and more.

Check out {url-home}[Asciidoctor]!

{summary}

=== Text Replacement

Claim your copyright (C), registered trademark (R) or trademark (TM) ... +
And don't forget about arrows -> <- => <=

:numbered!:

[appendix]
== Appendix

[bibliography]
[#bib]
== Bibliography

- [[[pp]]] Andy Hunt & Dave Thomas. The Pragmatic Programmer:
  From Journeyman to Master. Addison-Wesley. 1999.
- [[[gof,2]]] Erich Gamma, Richard Helm, Ralph Johnson & John Vlissides. Design Patterns:
  Elements of Reusable Object-Oriented Software. Addison-Wesley. 1994.

[glossary]
== Glossary

first term:: definition of first term
[[glossaryentry]]second term:: 
definition of second term