= Asciidoctor Demo

Richard <foo@bar.communicate>
:description: A demo of Asciidoctor. This document \
              exercises some features of AsciiDoc \
              so we can easily look them up here.
:library: Asciidoctor
:idprefix:
:numbered:
:imagesdir: images
:toc: preamble

////
This is a  multi-line comment.
////


// This is a single-line comment.


This Demo is inspired by the https://github.com/opendevise/asciidoc-samples/blob/master/demo.adoc[opendevice sample] and the link:https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[AsciiDoc Quick Reference].

It uses {library} {asciidoctor-version}.

TIP: This is a tip.
That is over now.

== Inline markup

*bold* and **b**older +
_italic_ and __i__talicer +
*_bold italic_*

There is also +
#highlight# +
[.small]#small print# and [.big]##B##ig print +
[.underline]#underline# and [.line-through]#line-through# +
^super^script and ~sub~script +
`monospace` and un``monospaced``

== Html

Place html +++<b>HTML</b>+++ directly.

== Text Replacement

Claim your copyright (C), registered trademark (R) or trademark (TM) ...
And don't forget about arrows -> <- => <=

== Links

Can go to external sites like link:http://google.com[Google] or to relative link:README.adoc[documents].

== Lists

Lists can be :
* unordered
** and nested
. Ordered
.. and nested

=== Checklist

* [*] checked
* [x] also checked
* [ ] not checked
*     normal list item

== Admonition

NOTE: This is a note

Here are the other built-in admonition types:

TIP: Pro tip...

IMPORTANT: Don't forget...

WARNING: Watch out for...

CAUTION: Ensure that...

[NOTE]
====
This is a longer note with

.A list
- one
- two
- three
====

== Quote

[quote, Charles Lutwidge Dodgson]
____
If you don't know where you are going, any road will get you there.
____

[quote, Albert Einstein]
A person who never made a mistake never tried anything new.

== Horizontal Rule

'''

== Definition

first term:: definition of first term
second term:: 
definition of second term

== Diagram

Diagrams can be drawn with mermaid
[mermaid, test, png]   
.... 
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
....

== Image

You can reference images image:icons/fontawesome/solid/anchor.svg[Anchor, title="Anchor"] inline or as a block:

.An amazing anchor
[#img-anchor]
[caption="Figure 1: "]
image::icons/fontawesome/solid/anchor.svg[Anchor,300,200]

== Videos

Embed them from Youtube or Vimeo.

video::rPQoq7ThGAU[youtube]

or

video::67480300[vimeo]

== Code

Reference code like `types` or `methods` inline 

or as a block with callouts

[source,ruby]
----
require 'sinatra' // <1>

get '/hi' do // <2>
  "Hello World!" // <3>
end
----
<1> Library import
<2> URL mapping
<3> HTTP response body

or directly from a file:

[source,ruby,indent=0]
----
include::lib/document.rb[lines=5..10]
----

== Tables

[cols="1,1,3", options="header"] 
.with three columns, a header, and one row of content
|===
|Name
|Role
|Description

|Lord McTavish
|Father
|An idiot. That's it.

|===

== Substitution

:url-home: https://asciidoctor.org
:summary: Asciidoctor is a mature, plain-text document format for \
     writing notes and more.

Check out {url-home}[Asciidoctor]!

{summary}

== Footnotes

A bold statement!footnoteref:[disclaimer,Opinions are my own.]

Another bold statement with a reused footnote.footnoteref:[disclaimer]

== Bibliography

_The Pragmatic Programmer_ <<pp>> should be required reading for all developers.
To learn all about design patterns, refer to the book by the "`Gang of Four`" <<gof>>.

[bibliography]
== References

- [[[pp]]] Andy Hunt & Dave Thomas. The Pragmatic Programmer:
  From Journeyman to Master. Addison-Wesley. 1999.
- [[[gof,2]]] Erich Gamma, Richard Helm, Ralph Johnson & John Vlissides. Design Patterns:
  Elements of Reusable Object-Oriented Software. Addison-Wesley. 1994.