= Coffee Book


A book for people that turn coffee into code. It's meant for user-need developers that want to look up things, find tidbits and links to further reading/hearing/watching material.

So far I have collected lots of interesting material but all in private, not visible to anyone but myself. I am sure many of you have done the same. That seems wasteful. I would like to change that.

For the english version please link:en/Intro.adoc[start here].

== Style

* Commits are made in the style of Angular.

== Assets

=== Icons

The free link:https://fontawesome.com/[Fontawesome] Icons are used for which the link:https://creativecommons.org/licenses/by/4.0/[CC by 4.0] applies. If you want to look for a new icon you should use the link:https://fontawesome.com/cheatsheet[Fontawesome Cheatsheet].

=== About AsciiDoc

This text is written in AsciiDoc. Here is a link to the link:https://asciidoctor.org/docs/asciidoc-writers-guide/[AsciiDoc Writer's Guide].
If you're just looking for a cheat sheet, check out the link:https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[AsciiDoc Quick Reference].

If you want to see source files other people wrote in asciidoc, please look at:

- link:https://github.com/asciidoctor/asciidoctor.org/blob/master/docs/what-is-asciidoc.adoc[AsciiDoctor]

=== AsciiDoc Demo

include::Demo.adoc[]