= Coffee Book

A book for people that turn coffee into code. It's meant for user-need developers that want to look up things, find tidbits and links to further reading/hearing/watching material.

So far I have collected lots of interesting material but all in private, not visible to anyone but myself. I am sure many of you have done the same. That seems wasteful. I would like to change that.

For the english version please link:en/Intro.adoc[start here].

If you want to see things that Github Flavored Asciidoc can do for you, you should check the link:Demo.adoc[demo]. 
Asciidoc is rather more powerful than Markdown, if you want to see a link:https://asciidoctor.org/docs/user-manual/#comparison-by-example[comparison].

== Conventions

=== Commit Messages
Since commit messages are all about documentation I do not follow a strict scheme like link:https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#-git-commit-guidelines[Angular Style Commits]. However I want to adopt the good behaviors from link:https://chris.beams.io/posts/git-commit/[How to Write a Git Commit Message]. 

The rules I adopted for commit messages are:

* Capitalize the subject line
* Do not end the subject line with a period
* Use the imperative mood in the subject line

`git commit -m "Fix typo in Demo"`

For now I see no point to adding a body explaining the *why*. But that will change should the book grow.

==== Examples

* Restructure document for better readability.
* Update getting started documentation
* Remove unused documents
* Release version 1.0.0


=== Writing Style

More concrete writing suggestions like link:https://wiki.openstack.org/wiki/Documentation/Conventions/Writing_style[this] could be added in the future.

=== Formatting

Depending on the text element you might want to:

* *draw attention* to it
* denote _technical terms, transliterations, thoughts, authors_
* inline `code references`

== Assets

=== Icons

The free link:https://fontawesome.com/[Fontawesome] Icons are used for which the link:https://creativecommons.org/licenses/by/4.0/[CC by 4.0] applies. If you want to look for a new icon you should use the link:https://fontawesome.com/cheatsheet[Fontawesome Cheatsheet].

=== About AsciiDoc

This text is written in AsciiDoc. Here is a link to the link:https://asciidoctor.org/docs/asciidoc-writers-guide/[AsciiDoc Writer's Guide].
If you're just looking for a cheat sheet, check out the link:https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[AsciiDoc Quick Reference].

If you want to see source files other people wrote in asciidoc, please look at:

- link:https://github.com/asciidoctor/asciidoctor.org/blob/master/docs/what-is-asciidoc.adoc[AsciiDoctor]